/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lnpgrvtobvrxzqvtlwzz"
export const supabaseUrl = `https://${projectId}.supabase.co`
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucGdydnRvYnZyeHpxdnRsd3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTgwNjksImV4cCI6MjA3MzMzNDA2OX0.dm6JokEGPBFf4fXbg_V8Z-UKC5QzwxbRPRHy0GROaDs"